[default_session]
startup_command = "nvim -c ':Telescope find_files'"

[[session]]
name = "Downloads 📥"
path = "~/Downloads"
startup_command = "ls"

[[session]]
name = "Dotfiles"
path = "~/dotfiles/"
startup_command = "v ."

[[session]]
name = "Monitoring-*"
path = "~/Projects/bmr_monitoring/"
startup_command = "source venv/bin/activate && v ."
