apiVersion: v1
generated: "2023-05-28T14:14:36.744175033+03:00"
repositories:
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: localstack
  pass_credentials_all: false
  password: ""
  url: https://helm.localstack.cloud/
  username: ""
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: prometheus-community
  pass_credentials_all: false
  password: ""
  url: https://prometheus-community.github.io/helm-charts
  username: ""
